#1.Import numpy library.

In [ ]:
import  numpy as np

#2.Create 1D array with 5 elements.

In [ ]:
oneD=np.array([1,3,4,5,6])
print(oneD)

[1 3 4 5 6]


#3.Create 1D array with 5 elements random value. (by default values between 0 to 1)

In [ ]:
random=np.random.rand(5)
print(random)

[0.15328851 0.15303961 0.70950541 0.82337824 0.2772061 ]


# 4.Generate random value from range 5 to 15 with 1D array size 10.

In [55]:
arr=np.array(np.random.randint(5,15,10))
print(arr)

[14  8 14 14  5 12 14  7  5 14]


#5.Create 2D array - 4 by 3 size.

In [ ]:
# prompt: Create 2D array - 4 by 3 size.

twoD=np.random.rand(4,3)
twoD


array([[0.74967984, 0.4899753 , 0.43301897],
       [0.16208499, 0.35012697, 0.17950222],
       [0.03297875, 0.43634302, 0.19720058],
       [0.80828843, 0.82785982, 0.04186385]])

#5.Create 2D array with size 3 by 3. Elements values are random number(by default values between 0 to 1)

In [ ]:
import numpy as np
random=np.random.rand(2 ,3)
print(random)

[[0.57064062 0.05473609 0.26195823]
 [0.79451335 0.27928439 0.09793998]]


#.7Generate random value from range 5 to 15 with 2D array size 3 by 3.

In [ ]:

arr = np.random.randint(5,15, size=(3,3))
arr

array([[ 5,  5, 11],
       [11, 14,  7],
       [ 8, 14,  7]])

#8.Create 3D array with size 2 * 3 * 2.

In [39]:
arr=np.random.rand(2,3,2)
arr

array([[[0.10984562, 0.66467624],
        [0.08218732, 0.88930998],
        [0.08532088, 0.24860373]],

       [[0.38210262, 0.00778725],
        [0.54544278, 0.92160355],
        [0.76042393, 0.07844371]]])

#9.Initialize 5 by 5 array with all values are zeros.


In [40]:
arr=np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#10.Initialize 5 by 5 array with all values are ones.

In [41]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#11.Initialize 5 by 5 array with all values are particular values(consider 4).

In [42]:
arr=np.full((5,5),4)
arr

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

#12.Create indentity matrix with all diagonal values are 1 and rest all values are zeros.

In [44]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#13.Find out shape of array.

In [46]:
print(arr.shape)

(5, 5)


#14.Find dimension of array.

In [47]:
print(arr.ndim)

2


#15.Find no. of elements of from above any array.

In [48]:
print(arr.size)

25


#16.Find type of array.

In [50]:
print(np.dtype)

<class 'numpy.dtype'>


#17.Find maximum value from array.

In [66]:
arr=np.random.randint(4,45 ,size=(3,3))
print(arr)
print(arr.max())

[[20 14 28]
 [40 20 37]
 [40  4 31]]
40


#18.Find minimum value from array.

In [67]:
print(arr.min())

4


#19.Find average (mean) values from array.

In [70]:
print(np.mean(arr))
print(arr.mean())
print(np.random.randint(12,34,size=(3,3)).mean())

26.0
26.0
22.88888888888889


#20.Find location of maximum value from array.

In [72]:
print(arr.argmax())
print(np.unravel_index(np.argmax(arr), arr.shape))

3
(1, 0)


#21.Create two 2D array of size 3 by 3 and perform four basic mathematical operations.

In [74]:
import numpy as np

# Create two 3x3 arrays
array1 = np.random.randint(1, 10, size=(3, 3))
array2 = np.random.randint(1, 10, size=(3, 3))
print(array1,"\n", array2)
# Addition
addition_result = array1 + array2
print("Addition:\n", addition_result)

# Subtraction
subtraction_result = array1 - array2
print("Subtraction:\n", subtraction_result)

# Multiplication (element-wise)
multiplication_result = array1 * array2
print("Element-wise Multiplication:\n", multiplication_result)

# Division (element-wise)
division_result = array1 / array2
print("Element-wise Division:\n", division_result)

[[6 8 3]
 [8 2 5]
 [2 4 3]] 
 [[6 4 2]
 [6 3 2]
 [2 6 1]]
Addition:
 [[12 12  5]
 [14  5  7]
 [ 4 10  4]]
Subtraction:
 [[ 0  4  1]
 [ 2 -1  3]
 [ 0 -2  2]]
Element-wise Multiplication:
 [[36 32  6]
 [48  6 10]
 [ 4 24  3]]
Element-wise Division:
 [[1.         2.         1.5       ]
 [1.33333333 0.66666667 2.5       ]
 [1.         0.66666667 3.        ]]


#22.Print index 2 and -2 value for 1D array. (indexing).

In [75]:

print(oneD[2])
oneD[-2]

4


5

#23.Perform indexing operations with 2D array.

In [76]:
# prompt: Perform indexing operations with 2D array.

import numpy as np

# Assuming 'arr' is your 2D array (replace with your actual array)
arr = np.random.randint(1, 10, size=(3,3)) # Example 3x3 array
print(arr)

# Accessing elements using row and column indices:

# Element at row 0, column 1
print(arr[0, 1])

# Element at row 2, column 2
print(arr[2, 2])

# Slicing rows:
# Get the first two rows
print(arr[:2])


# Slicing columns:
# Get the last two columns
print(arr[:, 1:])

# Slicing a sub-matrix
# Elements from rows 1-2 and columns 0-1
print(arr[1:3, :2])

# Negative Indexing:
# Element in the last row, second to last column
print(arr[-1, -2])

[[9 8 5]
 [4 5 7]
 [2 2 9]]
8
9
[[9 8 5]
 [4 5 7]]
[[8 5]
 [5 7]
 [2 9]]
[[4 5]
 [2 2]]
2


#24.Print value of index 2 to 5 (slicing)

In [79]:
print(oneD[2:5])

[4 5 6]


#25.Print from index 0 to 5 values

In [83]:
arr=np.array(np.random.randint(1,10 ,13))
arr
print(arr[0:6])

[5 8 5 1 5 6]


#26.Print from index 5 to all

In [85]:
print(arr[5:])

[6 7 3 5 1 7 4 6]


#27.Reassign value for particular index.

In [87]:
arr[6]=678
print(arr[3:9])

[  1   5   6 678   3   5]


#28: Reassign value 100 to all elements.

In [89]:
arr[:]
print(arr)

[100 100 100 100 100 100 100 100 100 100 100 100 100]


#29.Extract elements from index 1 to 7 with a step of 2.

In [91]:
arr=np.array(np.random.randint(12, 45,12))
print(arr[1:8:2])

[24 20 23 44]


#30.Print Reverse the array.

In [94]:
print(arr[::-1])

[32 37 29 12 44 28 23 35 20 44 24 24]
